import { normalizeForComparison } from './utils';

export const SCHOOL_CODSEC_MAP: Record<string, string> = {
  "ANEXO - CEMIT DE VIT.DA CONQUISTA - DIS. LAGOA DO TIMOTEO": "1179490",
  "ANEXO - CEMIT DE VIT.DA CONQUISTA - DISTRITO DE BANDEIRA NOVA": "1179429",
  "ANEXO - CEMIT DE VIT.DA CONQUISTA - POVOADO SOSSEGO": "1179723",
  "ANEXO - CEMIT DE VITORIA DA CONQUISTA - DISTRITO DE CERCADINHO": "1178183",
  "ANEXO - CEMIT DE VITORIA DA CONQUISTA - DISTRITO DE LAGOA DA SERRA": "1178771",
  "ANEXO - COL EST PADRE LUIS SOARES PALMEIRA-DISTRITO DE BATE PE": "1177015",
  "ANEXO - COL. EST DUQUE DE CAXIAS - POV DE JUREMA": "1178864",
  "ANEXO - COLEGIO EST. DO CAMPO DA CABECEIRA DA JIBOIA - DIST. CAPINAL": "1179475",
  "ANEXO - COLEGIO EST. ZULEIDE FREIRE DE ABREU - DIST DE IRUNDIARA": "1178861",
  "ANEXO - COLEGIO ESTADUAL ZULEIDE FREIRE DE ABREU - VILA PAIOL": "1179233",
  "ANEXO - COLEGIO ESTADUAL ZULEIDE FREIRE DE ABREU- DIST DE IRUNDIARA": "1178861",
  "ANEXO - COLEGIO ESTADUAL ZULEIDE FREIRE DE ABREU- DIST. DE IRUNDIARA": "1178861",
  "ANEXO - COLEGIO ESTADUAL ZULEIDE FREIRE DE ABREU- ITUMIRIM": "1178862",
  "ANEXO - COLEGIO ESTADUAL ZULEIDE FREIRE DE ABREU- São José": "1178863",
  "ANEXO -COLEGIO ESTADUAL DO CAMPO LUCIA ROCHA MACEDO- ASS. PATRIA LIVRE": "1179641",
  "ANEXO CEMIT DE VITDA CONQUISTA DIS LAGOA DO TIMOTEO": "1179490",
  "ANEXO COL EST ANISIO TEIXEIRA DISTRITO DE IGUA": "1178780",
  "ANEXO DO CENT REG - CEMIT DE VITÓRIA DA CONQUISTA -DIST BARRA DA ILHA": "1178769",
  "ANEXO DO CENTRO REGIONAL- CEMIT DE VITORIA DA CONQUISTA- DIS CACHOEIRA": "1178775",
  "ANEXO DO CENTRO REGIONAL- CEMIT DE VITORIA DA CONQUISTA- DIS ROÇADO GRANDE": "1179428",
  "ANEXO DO COLEGIO ESTADUAL ANTONIO GONCALVES-DIST NOVA BRASILIA": "1178774",
  "ANEXO DO COLEGIO ESTADUAL DE PLANALTO - ANEXO DO GERIBA": "1179450",
  "ANEXO- Col. Estadual de Tempo Integral de Licínio de Almeida-DISTRITO DE TAUAPE": "1179647",
  "CENT.REG.DE ENS.MEDIO COM INTERMEDIACAO TEC.-CEMIT DE VIT.DA CONQUISTA": "1179285",
  "CENTRO DE APOIO PEDAGOGICO ESPECIALIZADO": "1179790",
  "CENTRO JUVENIL DE CIENCIA E CULTURA-CJCC - VITORIA DA CONQUISTA": "1179448",
  "CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DE VITORIA DA CONQUISTA": "1125429",
  "Col. Est. do Campo Nancy de Castro Esteves - Distrito de Vila do Café": "1179271",
  "Col. Estadual de Tempo Inetegral de Caetanos": "1165722",
  "Col. Estadual de Tempo Integral Camillo de Jesus Lima": "1179223",
  "Col. Estadual de Tempo Integral Cordeiros": "1128924",
  "Col. Estadual de Tempo Integral de Anagé": "1124813",
  "Col. Estadual de Tempo Integral de Aracatu": "1123671",
  "Col. Estadual de Tempo Integral de Barra do Choça": "1124856",
  "Col. Estadual de Tempo Integral de Caetanos - Anexo Caldeirão": "1178763",
  "Col. Estadual de Tempo Integral de Cândido Sales": "1178438",
  "Col. Estadual de Tempo Integral de Condeúba": "1128878",
  "Col. Estadual de Tempo Integral de Licínio de Almeida": "1128460",
  "Col. Estadual de Tempo Integral de Mortugaba": "1129181",
  "Col. Estadual de Tempo Integral Padre Luis Soares Palmeira": "1165358",
  "Col. Estadual De Tempo Integral Roberto Santos": "1125186",
  "Col. Estadual do Campo de Educação Integral José Gonçalves": "1179224",
  "Col. Estadual do Campo Lúcia Rocha Macedo - Anexo: Boa sorte": "1179164",
  "Col. Estadual Dom Climério de Almeida Andrade": "1178119",
  "Col. Estadual Geovane Ferreira de Queiroz - Distrito Quaraçu": "1179137",
  "COLEGIO DA POLICIA MILITAR - CPM ERALDO TINOCO": "1125640",
  "COLEGIO EST DO CAMPO DA CABECEIRA DA JIBOIA - DIST CABECEIRA DA JIBOIA": "1179246",
  "COLEGIO ESTADUAL ANISIO TEIXEIRA": "1125496",
  "COLEGIO ESTADUAL ANTONIO GONCALVES": "1124929",
  "COLÉGIO ESTADUAL DE TEMPO INTEGRAL DE BOM JESUS DA SERRA": "1165706",
  "COLEGIO ESTADUAL DE TEMPO INTEGRAL DE MAETINGA": "1141815",
  "COLEGIO ESTADUAL DE TEMPO INTEGRAL DE PIRIPA": "1156634",
  "COLÉGIO ESTADUAL DE TEMPO INTEGRAL DE PLANALTO": "1124996",
  "COLEGIO ESTADUAL DE TEMPO INTEGRAL DE VITÓRIA DA CONQUISTA": "1125992",
  "COLÉGIO ESTADUAL DE TEMPO INTEGRAL PROFESSORA ELINEUZA DA SILVA FERREIRA": "1124872",
  "COLÉGIO ESTADUAL DE TEMPO INTEGRAL PROFESSORA ELINEUZA DA SILVA FERREIRA - Timbo": "1178762",
  "Colégio Estadual de Tempo Integral Professora Elizabeth Maria Couto": "1179822",
  "COLÉGIO ESTADUAL DO CAMPO DE TEMPO INTEGRAL DE PRESIDENTE JÂNIO QUADROS": "1178071",
  "Colégio Estadual Do Campo Erasmo Novais Dos Santos - Pradoso": "1125399",
  "COLEGIO ESTADUAL DO CAMPO GEOVANE FERREIRA DE QUEIROZ": "1179137",
  "COLEGIO ESTADUAL DO CAMPO LUCIA ROCHA MACEDO - TEMPO INTEGRAL - ASSENTAMENTO CANGUSSU": "1179113",
  "COLEGIO ESTADUAL DO CAMPO LUCIA ROCHA MACEDO - TEMPO INTEGRAL - ASSENTAMENTO LAGOA DO CALDEIRÃO": "1179165",
  "COLEGIO ESTADUAL DO CAMPO MAMEDIO BATISTA LOBAO": "1179136",
  "COLEGIO ESTADUAL DO CAMPO NANCY DE CASTRO ESTAVES": "1179271",
  "COLÉGIO ESTADUAL DOM CLIMÉRIO ALMEIDA DE ANDRADE TEMPO INTEGRAL": "1178119",
  "COLEGIO ESTADUAL DOUTOR ROBERTO SANTOS - TEMPO INTEGRAL": "1125186",
  "COLEGIO ESTADUAL EURIDES SANTANA - TEMPO INTEGRAL": "1125062",
  "COLEGIO ESTADUAL JORGE AMADO": "1178271",
  "COLEGIO ESTADUAL JOSE PALLES SOBRINHO - TEMPO INTEGRAL": "1165277",
  "COLEGIO ESTADUAL JOSE SA NUNES": "1125160",
  "COLEGIO ESTADUAL KLEBER PACHECO DE OLIVEIRA": "1125224",
  "COLEGIO ESTADUAL MARIETA PEREIRA DOS SANTOS - TEMPO INTEGRAL": "1178248",
  "COLEGIO ESTADUAL PETRINA NOVAIS SILVA CAIRO": "1177071",
  "COLEGIO ESTADUAL PROFESSOR DIOMAR SILVA BRITO - TEMPO INTEGRAL": "1178113",
  "COLEGIO ESTADUAL PROFESSORA HELEUSA FIGUEIRA CAMARA": "1176435",
  "COLEGIO ESTADUAL SISINIO RIBEIRO SILVA": "1178405",
  "COLEGIO ESTADUAL VITORIA LIMA DE OLIVEIRA - DISTRITO DE BARRA NOVA": "1178404",
  "COLEGIO ESTADUAL ZULEIDE FREIRE DE ABREU": "1176160",
  "COMPLEXO INTEGRADO DE EDUC BASICA PROFIS E TEC DE VITORIA DA CONQUISTA": "1125305",
  "POLO UAB - VITORIA DA CONQUISTA": "1183401",
  "SEDE NTE 20": "SEDE NTE 20"
};

export function getCodSecForSchool(schoolName: string): string {
  if (!schoolName) return "";
  const normalizedSearch = normalizeForComparison(schoolName);
  
  // Try exact match on key normalized
  for (const [key, val] of Object.entries(SCHOOL_CODSEC_MAP)) {
    if (normalizeForComparison(key) === normalizedSearch) {
      return val;
    }
  }
  
  // Fuzzy fallback: check if one contains the other
  for (const [key, val] of Object.entries(SCHOOL_CODSEC_MAP)) {
    const normalizedKey = normalizeForComparison(key);
    if (normalizedKey.includes(normalizedSearch) || normalizedSearch.includes(normalizedKey)) {
      return val;
    }
  }
  
  return "";
}
